import { User } from "../reducer/reducer";
import { v4 } from "uuid";
import { defaultState } from "../context/permissions_context";

export const dummyUsers: User[] = [
  {
    firstName: "Jason",
    lastName: "Todd",
    email: "jason.todd@gmail.com",
    id: v4(),
    imgUrl: "",
    role: "admin",
    status: true,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
  {
    firstName: "Irakli",
    lastName: "Ghachava",
    email: "irakli.ghachava@gmail.com",
    id: v4(),
    imgUrl: "",
    role: "user",
    status: false,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
  {
    firstName: "Abishek",
    lastName: "Shohat",
    email: "abishek@yahoo.com",
    id: v4(),
    imgUrl: "",
    role: "user",
    status: true,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
  {
    firstName: "Alan",
    lastName: "Walker",
    email: "walker@gmail.co.uk",
    id: v4(),
    imgUrl: "",
    role: "user",
    status: true,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
  {
    firstName: "Salvador",
    lastName: "Dali",
    email: "salvador@gmail.com",
    id: v4(),
    imgUrl: "",
    role: "admin",
    status: true,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
  {
    firstName: "Blaise",
    lastName: "Pascla",
    email: "b.pascal@gmail.com",
    id: v4(),
    imgUrl: "",
    role: "admin",
    status: true,
    superAdmin: false,
    permissions: defaultState.userPermissions,
  },
];
